name: Push
on:
  push:
    branches: [main]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Build and deploy to GitHub Pages
      run: npm run deploy
