name: Push
on:
  push:
    branches: [master]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - name: Build and deploy to GitHub Pages
      run: npm run deploy
